name: linuxday_2024_presentation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  elegant_notification: ^2.3.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_deck: ^0.16.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  local_notifier: ^0.1.6
  lottie: ^3.1.2
  pdfrx: ^1.0.84
  phosphor_flutter: ^2.1.0
  printing: ^5.13.3
  pub_api_client: ^2.7.1
  rive: ^0.13.14
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0
  window_manager: ^0.4.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdf/
    - assets/animations/
    - assets/svg/
    - assets/gifs/
