name: linuxday_2024_presentation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_deck: ^0.16.1
  flutter_riverpod: ^2.5.1
  get_it: ^8.0.0
  phosphor_flutter: ^2.1.0
  pub_api_client: ^2.7.1
  riverpod_annotation: ^2.3.5
  window_manager: ^0.4.2
  yaru: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
